openstreetmap-website/config/routes.rb
    get "changeset/:id" => "api/changesets#show", :as => :changeset_show, :id => /\d+/
    post "changeset/:id/subscribe" => "api/changesets#subscribe", :as => :changeset_subscribe, :id => /\d+/
    post "changeset/:id/unsubscribe" => "api/changesets#unsubscribe", :as => :changeset_unsubscribe, :id => /\d+/
    put "changeset/:id" => "api/changesets#update", :id => /\d+/
    put "changeset/:id/close" => "api/changesets#close", :as => :changeset_close, :id => /\d+/
    get "changesets" => "api/changesets#query"
    post "changeset/:id/comment" => "api/changeset_comments#create", :as => :changeset_comment, :id => /\d+/
    post "changeset/comment/:id/hide" => "api/changeset_comments#destroy", :as => :changeset_comment_hide, :id => /\d+/
    post "changeset/comment/:id/unhide" => "api/changeset_comments#restore", :as => :changeset_comment_unhide, :id => /\d+/

    put "node/create" => "api/nodes#create"
    get "node/:id/ways" => "api/ways#ways_for_node", :as => :node_ways, :id => /\d+/
    get "node/:id/relations" => "api/relations#relations_for_node", :as => :node_relations, :id => /\d+/
    get "node/:id/history" => "api/old_nodes#history", :as => :api_node_history, :id => /\d+/
    post "node/:id/:version/redact" => "api/old_nodes#redact", :as => :node_version_redact, :version => /\d+/, :id => /\d+/
    get "node/:id/:version" => "api/old_nodes#version", :as => :node_version, :id => /\d+/, :version => /\d+/
    get "node/:id" => "api/nodes#show", :as => :api_node, :id => /\d+/
    put "node/:id" => "api/nodes#update", :id => /\d+/
    delete "node/:id" => "api/nodes#delete", :id => /\d+/
    get "nodes" => "api/nodes#index"

    put "way/create" => "api/ways#create"
    get "way/:id/history" => "api/old_ways#history", :as => :api_way_history, :id => /\d+/
    get "way/:id/full" => "api/ways#full", :as => :way_full, :id => /\d+/
    get "way/:id/relations" => "api/relations#relations_for_way", :as => :way_relations, :id => /\d+/
    post "way/:id/:version/redact" => "api/old_ways#redact", :as => :way_version_redact, :version => /\d+/, :id => /\d+/
    get "way/:id/:version" => "api/old_ways#version", :as => :way_version, :id => /\d+/, :version => /\d+/
    get "way/:id" => "api/ways#show", :as => :api_way, :id => /\d+/
    put "way/:id" => "api/ways#update", :id => /\d+/
    delete "way/:id" => "api/ways#delete", :id => /\d+/
    get "ways" => "api/ways#index"

    put "relation/create" => "api/relations#create"
    get "relation/:id/relations" => "api/relations#relations_for_relation", :as => :relation_relations, :id => /\d+/
    get "relation/:id/history" => "api/old_relations#history", :as => :api_relation_history, :id => /\d+/
    get "relation/:id/full" => "api/relations#full", :as => :relation_full, :id => /\d+/
    post "relation/:id/:version/redact" => "api/old_relations#redact", :as => :relation_version_redact, :version => /\d+/, :id => /\d+/
    get "relation/:id/:version" => "api/old_relations#version", :as => :relation_version, :id => /\d+/, :version => /\d+/
    get "relation/:id" => "api/relations#show", :as => :api_relation, :id => /\d+/
    put "relation/:id" => "api/relations#update", :id => /\d+/
    delete "relation/:id" => "api/relations#delete", :id => /\d+/
    get "relations" => "api/relations#index"

    get "map" => "api/map#index"

    get "trackpoints" => "api/tracepoints#index"

    get "user/:id" => "api/users#show", :id => /\d+/, :as => :api_user
    get "user/details" => "api/users#details"
    get "user/gpx_files" => "api/users#gpx_files"
    get "users" => "api/users#index", :as => :api_users

    resources :user_preferences, :except => [:new, :create, :edit], :param => :preference_key, :path => "user/preferences", :controller => "api/user_preferences" do
      collection do
        put "" => "api/user_preferences#update_all", :as => ""
      end
    end

    post "gpx/create" => "api/traces#create"
    get "gpx/:id" => "api/traces#show", :as => :api_trace, :id => /\d+/
    put "gpx/:id" => "api/traces#update", :id => /\d+/
    delete "gpx/:id" => "api/traces#destroy", :id => /\d+/
    get "gpx/:id/details" => "api/traces#show", :id => /\d+/
    get "gpx/:id/data" => "api/traces#data", :as => :api_trace_data

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :constraints => { :id => /\d+/ }, :controller => "api/notes", :as => :api_notes do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end
    end

    post "notes/addPOIexec" => "api/notes#create"
    post "notes/closePOIexec" => "api/notes#close"
    post "notes/editPOIexec" => "api/notes#comment"
    get "notes/getGPX" => "api/notes#index", :format => "gpx"
    get "notes/getRSSfeed" => "api/notes#feed", :format => "rss"
  end

  # Data browsing
  get "/way/:id" => "browse#way", :id => /\d+/, :as => :way
  get "/way/:id/history" => "browse#way_history", :id => /\d+/, :as => :way_history
  get "/node/:id" => "browse#node", :id => /\d+/, :as => :node
  get "/node/:id/history" => "browse#node_history", :id => /\d+/, :as => :node_history
  get "/relation/:id" => "browse#relation", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "browse#relation_history", :id => /\d+/, :as => :relation_history
  get "/changeset/:id" => "browse#changeset", :as => :changeset, :id => /\d+/
  get "/changeset/:id/comments/feed" => "changeset_comments#index", :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => "rss" }
  resources :notes, :path => "note", :only => [:show, :new]

  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#index", :as => :user_notes
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"
  get "/about/:about_locale" => "site#about"
  get "/about" => "site#about"
  get "/communities" => "site#communities"
  get "/history" => "changesets#index"
  get "/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/history/comments/feed" => "changeset_comments#index", :as => :changesets_comments_feed, :defaults => { :format => "rss" }
  get "/export" => "site#export"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  match "/logout" => "sessions#destroy", :via => [:get, :post]
  get "/offline" => "site#offline"
  get "/key" => "site#key"
  get "/id" => "site#id"
  get "/query" => "browse#query"
  get "/user/new" => "users#new"
  post "/user/new" => "users#create"
  get "/user/terms" => "users#terms"
  post "/user/save" => "users#save"
  get "/user/:display_name/confirm/resend" => "confirmations#confirm_resend", :as => :user_confirm_resend
  match "/user/:display_name/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm-email" => "confirmations#confirm_email", :via => [:get, :post]
  post "/user/go_public" => "users#go_public"
  match "/user/reset-password" => "passwords#reset_password", :via => [:get, :post], :as => :user_reset_password
  match "/user/forgot-password" => "passwords#lost_password", :via => [:get, :post], :as => :user_forgot_password
  get "/user/suspended" => "users#suspended"

  get "/index.html", :to => redirect(:path => "/")
  get "/create-account.html", :to => redirect(:path => "/user/new")
  get "/forgot-password.html", :to => redirect(:path => "/user/forgot-password")

  # omniauth
  get "/auth/failure" => "users#auth_failure"
  match "/auth/:provider/callback" => "users#auth_success", :via => [:get, :post], :as => :auth_success
  match "/auth/:provider" => "users#auth", :via => [:post, :patch], :as => :auth

  # permalink
  get "/go/:code" => "site#permalink", :code => /[a-zA-Z0-9_@~]+[=-]*/, :as => :permalink

  # rich text preview
  post "/preview/:type" => "site#preview", :as => :preview

  # traces
  resources :traces, :except => [:show]
  get "/user/:display_name/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/

openstreetmap-website/app/controllers/api/users_controller.rb
module Api
  class UsersController < ApiController
    before_action :check_api_readable
    before_action :disable_terms_redirect, :only => [:details]
    before_action :setup_user_auth, :only => [:show, :index]
    before_action :authorize, :only => [:details, :gpx_files]

    authorize_resource

    around_action :api_call_handle_error
    before_action :lookup_user_by_id, :only => [:show]

    before_action :set_request_formats, :except => [:gpx_files]

    def index
      raise OSM::APIBadUserInput, "The parameter users is required, and must be of the form users=id[,id[,id...]]" unless params["users"]

      ids = params["users"].split(",").collect(&:to_i)

      raise OSM::APIBadUserInput, "No users were given to search for" if ids.empty?

      @users = User.visible.find(ids)

      # Render the result
      respond_to do |format|
        format.xml
        format.json
      end
    end

    def show
      if @user.visible?
        # Render the result
        respond_to do |format|
          format.xml
          format.json
        end
      else
        head :gone
      end
    end

    def details
      @user = current_user
      # Render the result
      respond_to do |format|
        format.xml { render :show }
        format.json { render :show }
      end
    end

    def gpx_files
      @traces = current_user.traces.reload
      render :content_type => "application/xml"
    end

    private

    ##
    # ensure that there is a "user" instance variable
    def lookup_user_by_id
      @user = User.find(params[:id])
    end

    ##
    #
    def disable_terms_redirect
      # this is necessary otherwise going to the user terms page, when
      # having not agreed already would cause an infinite redirect loop.
      # it's .now so that this doesn't propagate to other pages.
      flash.now[:skip_terms] = true
    end
  end
end

openstreetmap-website/app/helpers/user_helper.rb
module UserHelper
  # User images

  def user_image(user, options = {})
    options[:class] ||= "user_image border border-grey"
    options[:alt] ||= ""

    if user.image_use_gravatar
      user_gravatar_tag(user, options)
    elsif user.avatar.attached?
      user_avatar_variant_tag(user, { :resize_to_limit => [100, 100] }, options)
    else
      image_tag "avatar_large.png", options.merge(:width => 100, :height => 100)
    end
  end

  def user_thumbnail(user, options = {})
    options[:class] ||= "user_thumbnail border border-grey"
    options[:alt] ||= ""

    if user.image_use_gravatar
      user_gravatar_tag(user, options.merge(:size => 50))
    elsif user.avatar.attached?
      user_avatar_variant_tag(user, { :resize_to_limit => [50, 50] }, options)
    else
      image_tag "avatar_small.png", options.merge(:width => 50, :height => 50)
    end
  end

  def user_thumbnail_tiny(user, options = {})
    options[:class] ||= "user_thumbnail_tiny border border-grey"
    options[:alt] ||= ""

    if user.image_use_gravatar
      user_gravatar_tag(user, options.merge(:size => 50))
    elsif user.avatar.attached?
      user_avatar_variant_tag(user, { :resize_to_limit => [50, 50] }, options)
    else
      image_tag "avatar_small.png", options.merge(:width => 50, :height => 50)
    end
  end

  def user_image_url(user, options = {})
    if user.image_use_gravatar
      user_gravatar_url(user, options)
    elsif user.avatar.attached?
      polymorphic_url(user_avatar_variant(user, :resize_to_limit => [100, 100]), :host => Settings.server_url)
    else
      image_url("avatar_large.png")
    end
  end

  # External authentication support

  def openid_logo
    image_tag "openid_small.png", :alt => t("sessions.new.openid_logo_alt"), :class => "openid_logo"
  end

  def auth_button(name, provider, options = {})
    link_to(
      image_tag("#{name}.svg", :alt => t("sessions.new.auth_providers.#{name}.alt"), :class => "rounded-3"),
      auth_path(options.merge(:provider => provider)),
      :method => :post,
      :class => "auth_button",
      :title => t("sessions.new.auth_providers.#{name}.title")
    )
  end

  private

  # Local avatar support
  def user_avatar_variant_tag(user, variant_options, options)
    if user.avatar.variable?
      variant = user.avatar.variant(variant_options)
      # https://stackoverflow.com/questions/61893089/get-metadata-of-active-storage-variant/67228171
      if variant.processed?
        metadata = variant.processed.send(:record).image.blob.metadata
        if metadata["width"]
          options[:width] = metadata["width"]
          options[:height] = metadata["height"]
        end
      end
      image_tag variant, options
    else
      image_tag user.avatar, options
    end
  end

  def user_avatar_variant(user, options)
    if user.avatar.variable?
      user.avatar.variant(options)
    else
      user.avatar
    end
  end

  # Gravatar support

  # See http://en.gravatar.com/site/implement/images/ for details.
  def user_gravatar_url(user, options = {})
    size = options[:size] || 100
    hash = Digest::MD5.hexdigest(user.email.downcase)
    default_image_url = image_url("avatar_large.png")
    "#{request.protocol}www.gravatar.com/avatar/#{hash}.jpg?s=#{size}&d=#{u(default_image_url)}"
  end

  def user_gravatar_tag(user, options = {})
    url = user_gravatar_url(user, options)
    options[:height] = options[:width] = options.delete(:size) || 100
    image_tag url, options
  end
end

openstreetmap-website/app/views/users/_auth_association.html.erb
<p><%= t ".heading" %></p>
<p><%= t ".option_1" %></p>
<p><%= t ".option_2" %></p>

openstreetmap-website/app/views/users/_terms.html.erb
<p id="first">
  <%= @text["intro"] %>
  <%= @text["next_with_decline"] %>
</p>
<h3><%= @text["introduction"] %></h3>
<ol>
  <li>
    <p><%= @text["section_1"] %></p>
    <% unless @text['section_1a'].nil? %>
    <ol>
      <li><%= @text["section_1a"] %></li>
      <li><%= @text["section_1b"] %></li>
    </ol>
    <% end %>
  </li>
</ol>
<h3><%= @text["rights_granted"] %></h3>
<ol start="2">
  <li>
    <p><%= @text["section_2"] %></p>
  </li>
  <li>
    <p><%= @text["section_3"] %></p>
    <p><%= @text["active_defn_1"] %></p>
    <p><%= @text["active_defn_2"] %></p>
    </ul>
  </li>
  <li>
    <p><%= @text["section_4"] %></p>
  </li>
  <li>
    <p><%= @text["section_5"] %></p>
  </li>
</ol>
<h3><%= @text["limitation_of_liability"] %></h3>
<ol start="6">
  <li><p><%= @text["section_6"] %></p></li>
  <li><p><%= @text["section_7"] %></p></li>
</ol>
<h3><%= @text["miscellaneous"] %></h3>
<ol start="8">
  <li>
    <p id="last"><%= @text["section_8"] %></p>
  </li>
</ol>

openstreetmap-website/app/views/users/_terms_declined_flash.html.erb
<%= t ".terms_declined_html", :terms_declined_link => link_to(t(".terms_declined_link"), t(".terms_declined_url")) %>

openstreetmap-website/app/views/users/_user.html.erb
<tr>
  <td>
    <%= user_thumbnail(user) %>
  </td>
  <td>
    <p>
      <% if user.creation_ip %>
        <%= t "users.index.summary_html",
              :name => link_to(user.display_name, user_path(user)),
              :ip_address => link_to(user.creation_ip, :ip => user.creation_ip),
              :date => l(user.created_at, :format => :friendly) %>
      <% else %>
        <%= t "users.index.summary_no_ip_html",
              :name => link_to(user.display_name, user_path(user)),
              :date => l(user.created_at, :format => :friendly) %>
      <% end %>
    </p>
    <div class="richtext text-break"><%= user.description.to_html %></div>
  </td>
  <td>
    <%= check_box_tag "user_#{user.id}", "", false, :name => "user[#{user.id}]" %>
  </td>
</tr>

openstreetmap-website/app/views/users/blocked.html.erb
<% content_for :heading_class, "pb-0" %>
<% content_for :heading do %>
  <div class='header-illustration new-user-main'>
    <h1><%= t "users.new.title" %></h1>
  </div>
  <div class='header-illustration new-user-arm'></div>
<% end %>

<div class="message">
  <h1><%= t "users.new.no_auto_account_create" %></h1>
  <h2><%= t "users.new.please_contact_support_html", :support_link => mail_to(Settings.support_email, t("users.new.support")) %></h2>
</div>

openstreetmap-website/app/views/users/index.html.erb
<% @title = t(".title") %>

<% content_for :head do %>
  <%= javascript_include_tag "user" %>
<% end %>

<% content_for :heading do %>
  <h1><%= t(".heading") %></h1>
<% end %>

<% unless @users.empty? %>
  <%= form_tag do %>
    <%= hidden_field_tag :status, params[:status] if params[:status] %>
    <%= hidden_field_tag :ip, params[:ip] if params[:ip] %>
    <%= hidden_field_tag :page, params[:page] if params[:page] %>
    <table id="user_list" class="table table-borderless table-striped">
      <thead>
        <tr>
          <td colspan="2">
            <%= t ".showing",
                  :page => @user_pages.current_page.number,
                  :first_item => @user_pages.current_page.first_item,
                  :last_item => @user_pages.current_page.last_item,
                  :items => @user_pages.item_count,
                  :count => @user_pages.current_page.last_item - @user_pages.current_page.first_item + 1 %>
            <% if @user_pages.page_count > 1 %>
            | <%= raw pagination_links_each(@user_pages, {}) { |n| link_to n, @params.merge(:page => n) } %>
            <% end %>
          </td>
          <td>
            <%= check_box_tag "user_all", "1", false %>
          </td>
        </tr>
      </thead>
      <%= render @users %>
    </table>

    <div>
      <%= submit_tag t(".confirm"), :name => "confirm", :class => "btn btn-primary" %>
      <%= submit_tag t(".hide"), :name => "hide", :class => "btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <p><%= t ".empty" %></p>
<% end %>

openstreetmap-website/app/views/users/show.html.erb
<% content_for :heading do %>
  <div class="row">
    <div class="col-sm-auto">
      <%= user_image @user %>
    </div>
    <div class="col">
      <h1><%= @user.display_name %> <%= role_icons(@user) %></h1>
      <% if current_user and @user.id == current_user.id %>
        <!-- Displaying user's own profile page -->
        <nav class='secondary-actions'>
          <ul class='clearfix'>
            <li>
              <%= link_to t(".my edits"), :controller => "changesets", :action => "index", :display_name => current_user.display_name %>
              <span class='count-number'><%= number_with_delimiter(current_user.changesets.size) %></span>
            </li>
            <li>
              <%= link_to t(".my notes"), user_notes_path(@user) %>
            </li>
            <li>
              <%= link_to t(".my traces"), :controller => "traces", :action => "mine" %>
              <span class='count-number'><%= number_with_delimiter(current_user.traces.size) %></span>
            </li>
            <li>
              <%= link_to t(".my diary"), :controller => "diary_entries", :action => "index", :display_name => current_user.display_name %>
              <span class='count-number'><%= number_with_delimiter(current_user.diary_entries.size) %></span>
            </li>
            <li>
              <%= link_to t(".my comments"), diary_comments_path(current_user) %>
            </li>
            <li>
              <%= link_to t(".my settings"), edit_account_path %>
            </li>

            <% if current_user.blocks.exists? %>
              <li>
                <%= link_to t(".blocks on me"), user_blocks_on_path(current_user) %>
                <span class='count-number'><%= number_with_delimiter(current_user.blocks.active.size) %></span>
              </li>
            <% end %>

            <% if can?(:create, UserBlock) and current_user.blocks_created.exists? %>
              <li>
                <%= link_to t(".blocks by me"), user_blocks_by_path(current_user) %>
                <span class='count-number'><%= number_with_delimiter(current_user.blocks_created.active.size) %></span>
              </li>
            <% end %>

          </ul>
        </nav>

        <% else %>
        <!-- Displaying user profile page to the public -->
        <nav class='secondary-actions'>
          <ul class='clearfix'>

            <li>
              <%= link_to t(".edits"), :controller => "changesets", :action => "index", :display_name => @user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@user.changesets.size) %></span>
            </li>
            <li>
              <%= link_to t(".notes"), user_notes_path(@user) %>
            </li>
            <li>
              <%= link_to t(".traces"), :controller => "traces", :action => "index", :display_name => @user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@user.traces.size) %></span>
            </li>

            <!-- Displaying another user's profile page -->

            <li>
              <%= link_to t(".send message"), new_message_path(@user) %>
            </li>
            <li>
              <%= link_to t(".diary"), :controller => "diary_entries", :action => "index", :display_name => @user.display_name %>
              <span class='count-number'><%= number_with_delimiter(@user.diary_entries.size) %></span>
            </li>
            <li>
              <%= link_to t(".comments"), diary_comments_path(@user) %>
            </li>
            <li>
              <% if current_user and current_user.friends_with?(@user) %>
                <%= link_to t(".remove as friend"), remove_friend_path(:display_name => @user.display_name), :method => :post %>
              <% elsif current_user %>
                <%= link_to t(".add as friend"), make_friend_path(:display_name => @user.display_name), :method => :post %>
              <% else %>
                <%= link_to t(".add as friend"), make_friend_path(:display_name => @user.display_name) %>
              <% end %>
            </li>

            <% if @user.blocks.exists? %>
              <li>
                <%= link_to t(".block_history"), user_blocks_on_path(@user) %>
                <span class='count-number'><%= number_with_delimiter(@user.blocks.active.size) %></span>
              </li>
            <% end %>

            <% if @user.moderator? and @user.blocks_created.exists? %>
              <li>
                <%= link_to t(".moderator_history"), user_blocks_by_path(@user) %>
                <span class='count-number'><%= number_with_delimiter(@user.blocks_created.active.size) %></span>
              </li>
            <% end %>

            <% if can?(:create, UserBlock) %>
              <li>
                <%= link_to t(".create_block"), new_user_block_path(@user) %>
              </li>
            <% end %>

            <% if current_user and @user.id != current_user.id %>
              <li>
                <%= report_link(t(".report"), @user) %>
              </li>
            <% end %>
          </ul>
        </nav>
      <% end %>

      <div class='text-muted'>
        <small>
          <dl class="dl-inline">
            <dt><%= t ".mapper since" %></dt>
            <dd><%= l @user.created_at.to_date, :format => :long %></dd>
            <% unless @user.terms_agreed %>
              <dt><%= t ".ct status" %></dt>
              <dd>
                <% if @user.terms_seen? -%>
                  <%= t ".ct declined" %>
                <% else -%>
                  <%= t ".ct undecided" %>
                <% end -%>
              </dd>
            <% end -%>
          </dl>
        </small>
      </div>

      <% if can?(:set_status, User) || can?(:destroy, User) %>
        <nav class='secondary-actions'>
          <ul class='clearfix'>
            <% if can? :set_status, User %>
              <% if @user.may_activate? %>
                <li>
                  <%= link_to t(".activate_user"), set_status_user_path(:event => "activate", :display_name => @user.display_name), :method => :post, :data => { :confirm => t(".confirm") } %>
                </li>
              <% end %>

              <% if @user.may_unsuspend? %>
                <li>
                  <%= link_to t(".unsuspend_user"), set_status_user_path(:event => "unsuspend", :display_name => @user.display_name), :method => :post, :data => { :confirm => t(".confirm") } %>
                </li>
              <% end %>

              <% if @user.may_confirm? %>
                <li>
                  <%= link_to t(".confirm_user"), set_status_user_path(:event => "confirm", :display_name => @user.display_name), :method => :post, :data => { :confirm => t(".confirm") } %>
                </li>
              <% end %>

              <% if @user.may_unconfirm? %>
                <li>
                  <%= link_to t(".unconfirm_user"), set_status_user_path(:event => "unconfirm", :display_name => @user.display_name), :method => :post, :data => { :confirm => t(".confirm") } %>
                </li>
              <% end %>

              <% if @user.may_hide? %>
                <li>
                  <%= link_to t(".hide_user"), set_status_user_path(:event => "hide", :display_name => @user.display_name), :method => :post, :data => { :confirm => t(".confirm") } %>
                </li>
              <% end %>

              <% if @user.may_unhide? %>
                <li>
                  <%= link_to t(".unhide_user"), set_status_user_path(:event => "unhide", :display_name => @user.display_name), :method => :post, :data => { :confirm => t(".confirm") } %>
                </li>
              <% end %>
            <% end %>

            <% if can?(:destroy, User) && @user.may_soft_destroy? %>
              <li>
                <%= link_to t(".delete_user"), user_path(:display_name => @user.display_name), :method => :delete, :data => { :confirm => t(".confirm") } %>
              </li>
            <% end %>
          </ul>
        </nav>
      <% end %>

      <% if current_user and current_user.administrator? -%>
        <div class='text-muted'>
          <small>
            <dl class='dl-inline'>
              <dt><%= t ".email address" %></dt>
              <dd><%= @user.email %></dd>
              <% unless @user.creation_ip.nil? -%>
                <dt><%= t ".created from" %></dt>
                <dd><%= @user.creation_ip %></dd>
              <% end -%>
              <dt><%= t ".status" %></dt>
              <dd><%= @user.status.capitalize %></dd>
              <dt><%= t ".spam score" %></dt>
              <dd><%= @user.spam_score %></dd>
            </dl>
          </small>
        </div>
      <% end -%>
    </div>
  </div>
<% end %>

<div class="richtext text-break clearfix"><%= @user.description.to_html %></div>

<% if current_user and @user.id == current_user.id %>
  <div class="my-3">
    <%= link_to t(".edit_profile"), edit_profile_path, :class => "btn btn-outline-primary" %>
  </div>
<% end %>