openstreetmap-website/config/routes.rb
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"
  get "/about/:about_locale" => "site#about"
  get "/about" => "site#about"
  get "/communities" => "site#communities"
  get "/history" => "changesets#index"
  get "/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/history/comments/feed" => "changeset_comments#index", :as => :changesets_comments_feed, :defaults => { :format => "rss" }
  get "/export" => "site#export"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  match "/logout" => "sessions#destroy", :via => [:get, :post]
  get "/offline" => "site#offline"
  get "/key" => "site#key"
  get "/id" => "site#id"
  get "/query" => "browse#query"
  get "/user/new" => "users#new"
  post "/user/new" => "users#create"
  get "/user/terms" => "users#terms"
  post "/user/save" => "users#save"
  get "/user/:display_name/confirm/resend" => "confirmations#confirm_resend", :as => :user_confirm_resend
  match "/user/:display_name/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm" => "confirmations#confirm", :via => [:get, :post]
  match "/user/confirm-email" => "confirmations#confirm_email", :via => [:get, :post]
  post "/user/go_public" => "users#go_public"
  match "/user/reset-password" => "passwords#reset_password", :via => [:get, :post], :as => :user_reset_password
  match "/user/forgot-password" => "passwords#lost_password", :via => [:get, :post], :as => :user_forgot_password
  get "/user/suspended" => "users#suspended"

  get "/index.html", :to => redirect(:path => "/")
  get "/create-account.html", :to => redirect(:path => "/user/new")
  get "/forgot-password.html", :to => redirect(:path => "/user/forgot-password")

  # omniauth
  get "/auth/failure" => "users#auth_failure"
  match "/auth/:provider/callback" => "users#auth_success", :via => [:get, :post], :as => :auth_success
  match "/auth/:provider" => "users#auth", :via => [:post, :patch], :as => :auth

  # permalink
  get "/go/:code" => "site#permalink", :code => /[a-zA-Z0-9_@~]+[=-]*/, :as => :permalink

  # rich text preview
  post "/preview/:type" => "site#preview", :as => :preview

  # traces
  resources :traces, :except => [:show]
  get "/user/:display_name/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/user/:display_name/traces/tag/:tag" => "traces#index"
  get "/user/:display_name/traces/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/user/:display_name/traces" => "traces#index"
  get "/user/:display_name/traces/tag/:tag/rss" => "traces#georss", :defaults => { :format => :rss }
  get "/user/:display_name/traces/rss" => "traces#georss", :defaults => { :format => :rss }
  get "/user/:display_name/traces/:id" => "traces#show", :as => "show_trace"
  get "/user/:display_name/traces/:id/picture" => "traces#picture", :as => "trace_picture"
  get "/user/:display_name/traces/:id/icon" => "traces#icon", :as => "trace_icon"
  get "/traces/tag/:tag/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/traces/tag/:tag" => "traces#index"
  get "/traces/page/:page" => "traces#index", :page => /[1-9][0-9]*/
  get "/traces/tag/:tag/rss" => "traces#georss", :defaults => { :format => :rss }
  get "/traces/rss" => "traces#georss", :defaults => { :format => :rss }
  get "/traces/mine/tag/:tag/page/:page" => "traces#mine", :page => /[1-9][0-9]*/
  get "/traces/mine/tag/:tag" => "traces#mine"
  get "/traces/mine/page/:page" => "traces#mine"
  get "/traces/mine" => "traces#mine"
  get "/trace/create", :to => redirect(:path => "/traces/new")
  get "/trace/:id/data" => "traces#data", :id => /\d+/, :as => "trace_data"
  get "/trace/:id/edit", :to => redirect(:path => "/traces/%{id}/edit")

  # diary pages
  resources :diary_entries, :path => "diary", :only => [:new, :create, :index] do
    collection do
      get "friends" => "diary_entries#index", :friends => true
      get "nearby" => "diary_entries#index", :nearby => true
    end
  end
  get "/user/:display_name/diary/rss" => "diary_entries#rss", :defaults => { :format => :rss }
  get "/diary/:language/rss" => "diary_entries#rss", :defaults => { :format => :rss }
  get "/diary/rss" => "diary_entries#rss", :defaults => { :format => :rss }
  get "/user/:display_name/diary/comments/:page" => "diary_entries#comments", :page => /[1-9][0-9]*/
  get "/user/:display_name/diary/comments/" => "diary_entries#comments", :as => :diary_comments
  get "/user/:display_name/diary" => "diary_entries#index"
  get "/diary/:language" => "diary_entries#index"
  scope "/user/:display_name" do
    resources :diary_entries, :path => "diary", :only => [:edit, :update, :show], :id => /\d+/
  end
  post "/user/:display_name/diary/:id/newcomment" => "diary_entries#comment", :id => /\d+/, :as => :comment_diary_entry
  post "/user/:display_name/diary/:id/hide" => "diary_entries#hide", :id => /\d+/, :as => :hide_diary_entry
  post "/user/:display_name/diary/:id/unhide" => "diary_entries#unhide", :id => /\d+/, :as => :unhide_diary_entry
  post "/user/:display_name/diary/:id/hidecomment/:comment" => "diary_entries#hidecomment", :id => /\d+/, :comment => /\d+/, :as => :hide_diary_comment
  post "/user/:display_name/diary/:id/unhidecomment/:comment" => "diary_entries#unhidecomment", :id => /\d+/, :comment => /\d+/, :as => :unhide_diary_comment
  post "/user/:display_name/diary/:id/subscribe" => "diary_entries#subscribe", :as => :diary_entry_subscribe, :id => /\d+/
  post "/user/:display_name/diary/:id/unsubscribe" => "diary_entries#unsubscribe", :as => :diary_entry_unsubscribe, :id => /\d+/

  # user pages
  resources :users, :path => "user", :param => :display_name, :only => [:show, :destroy]
  get "/user/:display_name/account", :to => redirect(:path => "/account/edit")
  post "/user/:display_name/set_status" => "users#set_status", :as => :set_status_user

  resource :account, :only => [:edit, :update, :destroy]

  namespace :account do
    resource :deletion, :only => [:show]
  end
  resource :dashboard, :only => [:show]
  resource :preferences, :only => [:show, :edit, :update]
  resource :profile, :only => [:edit, :update]

  # friendships
  match "/user/:display_name/make_friend" => "friendships#make_friend", :via => [:get, :post], :as => "make_friend"
  match "/user/:display_name/remove_friend" => "friendships#remove_friend", :via => [:get, :post], :as => "remove_friend"

  # user lists
  match "/users" => "users#index", :via => [:get, :post]
  match "/users/:status" => "users#index", :via => [:get, :post]

  # geocoder
  get "/search" => "geocoder#search"
  post "/geocoder/search_latlon" => "geocoder#search_latlon"
  post "/geocoder/search_osm_nominatim" => "geocoder#search_osm_nominatim"
  post "/geocoder/search_osm_nominatim_reverse" => "geocoder#search_osm_nominatim_reverse"

  # directions
  get "/directions" => "directions#search"

  # export
  post "/export/finish" => "export#finish"
  get "/export/embed" => "export#embed"

  # messages
  resources :messages, :only => [:create, :show, :destroy] do
    post :mark
    match :reply, :via => [:get, :post]
    collection do
      get :inbox
      get :outbox
    end
  end
  get "/user/:display_name/inbox", :to => redirect(:path => "/messages/inbox")
  get "/user/:display_name/outbox", :to => redirect(:path => "/messages/outbox")
  get "/message/new/:display_name" => "messages#new", :as => "new_message"
  get "/message/read/:message_id", :to => redirect(:path => "/messages/%{message_id}")

  # oauth admin pages (i.e: for setting up new clients, etc...)
  scope "/user/:display_name" do
    resources :oauth_clients
  end
  match "/oauth/revoke" => "oauth#revoke", :via => [:get, :post]
  match "/oauth/authorize" => "oauth#authorize", :via => [:get, :post], :as => :authorize
  get "/oauth/token" => "oauth#token", :as => :token
  match "/oauth/request_token" => "oauth#request_token", :via => [:get, :post], :as => :request_token
  match "/oauth/access_token" => "oauth#access_token", :via => [:get, :post], :as => :access_token
  get "/oauth/test_request" => "oauth#test_request", :as => :test_request

  # roles and banning pages
  post "/user/:display_name/role/:role/grant" => "user_roles#grant", :as => "grant_role"
  post "/user/:display_name/role/:role/revoke" => "user_roles#revoke", :as => "revoke_role"
  get "/user/:display_name/blocks" => "user_blocks#blocks_on", :as => "user_blocks_on"
  get "/user/:display_name/blocks_by" => "user_blocks#blocks_by", :as => "user_blocks_by"
  get "/blocks/new/:display_name" => "user_blocks#new", :as => "new_user_block"
  resources :user_blocks
  match "/blocks/:id/revoke" => "user_blocks#revoke", :via => [:get, :post], :as => "revoke_user_block"

  # issues and reports
  resources :issues do
    resources :comments, :controller => :issue_comments
    member do
      post "resolve"
      post "assign"
      post "ignore"
      post "reopen"
    end
  end

  resources :reports

  # redactions
  resources :redactions

  # errors
  match "/403", :to => "errors#forbidden", :via => :all

openstreetmap-website/app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                :bigint(8)        not null, primary key
#  from_user_id      :bigint(8)        not null
#  title             :string           not null
#  body              :text             not null
#  sent_on           :datetime         not null
#  message_read      :boolean          default(FALSE), not null
#  to_user_id        :bigint(8)        not null
#  to_user_visible   :boolean          default(TRUE), not null
#  from_user_visible :boolean          default(TRUE), not null
#  body_format       :enum             default("markdown"), not null
#
# Indexes
#
#  messages_from_user_id_idx  (from_user_id)
#  messages_to_user_id_idx    (to_user_id)
#
# Foreign Keys
#
#  messages_from_user_id_fkey  (from_user_id => users.id)
#  messages_to_user_id_fkey    (to_user_id => users.id)
#

class Message < ApplicationRecord
  belongs_to :sender, :class_name => "User", :foreign_key => :from_user_id
  belongs_to :recipient, :class_name => "User", :foreign_key => :to_user_id

  validates :title, :presence => true, :utf8 => true, :length => 1..255
  validates :body, :sent_on, :presence => true
  validates :title, :body, :characters => true

  def self.from_mail(mail, from, to)
    if mail.multipart?
      if mail.text_part
        body = mail.text_part.decoded
      elsif mail.html_part
        body = HTMLEntities.new.decode(Sanitize.clean(mail.html_part.decoded))
      end
    elsif mail.text? && mail.sub_type == "html"
      body = HTMLEntities.new.decode(Sanitize.clean(mail.decoded))
    else
      body = mail.decoded
    end

    Message.new(
      :sender => from,
      :recipient => to,
      :sent_on => mail.date.new_offset(0),
      :title => mail.subject.sub(/\[OpenStreetMap\] */, ""),
      :body => body,
      :body_format => "text"
    )
  end

  def body
    RichText.new(self[:body_format], self[:body])
  end

  def digest
    md5 = Digest::MD5.new
    md5 << from_user_id.to_s
    md5 << to_user_id.to_s
    md5 << sent_on.xmlschema
    md5 << title
    md5 << body
    md5.hexdigest
  end
end

openstreetmap-website/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout "site"

  before_action :authorize_web
  before_action :set_locale

  authorize_resource

  before_action :lookup_user, :only => [:new, :create]
  before_action :check_database_readable
  before_action :check_database_writable, :only => [:new, :create, :reply, :mark, :destroy]
  before_action :allow_thirdparty_images, :only => [:new, :create, :show]

  # Show a message
  def show
    @title = t ".title"
    @message = Message.find(params[:id])

    if @message.recipient == current_user || @message.sender == current_user
      @message.message_read = true if @message.recipient == current_user
      @message.save
    else
      flash[:notice] = t ".wrong_user", :user => current_user.display_name
      redirect_to login_path(:referer => request.fullpath)
    end
  rescue ActiveRecord::RecordNotFound
    @title = t "messages.no_such_message.title"
    render :action => "no_such_message", :status => :not_found
  end

  # Allow the user to write a new message to another user.
  def new
    @message = Message.new(message_params.merge(:recipient => @user))
    @title = t ".title"
  end

  def create
    @message = Message.new(message_params)
    @message.recipient = @user
    @message.sender = current_user
    @message.sent_on = Time.now.utc

    if current_user.sent_messages.where("sent_on >= ?", Time.now.utc - 1.hour).count >= current_user.max_messages_per_hour
      flash.now[:error] = t ".limit_exceeded"
      render :action => "new"
    elsif @message.save
      flash[:notice] = t ".message_sent"
      UserMailer.message_notification(@message).deliver_later
      redirect_to :action => :inbox
    else
      @title = t "messages.new.title"
      render :action => "new"
    end
  end

  # Destroy the message.
  def destroy
    @message = Message.where("to_user_id = ? OR from_user_id = ?", current_user.id, current_user.id).find(params[:id])
    @message.from_user_visible = false if @message.sender == current_user
    @message.to_user_visible = false if @message.recipient == current_user
    if @message.save && !request.xhr?
      flash[:notice] = t ".destroyed"

      referer = safe_referer(params[:referer]) if params[:referer]

      redirect_to referer || { :action => :inbox }
    end
  rescue ActiveRecord::RecordNotFound
    @title = t "messages.no_such_message.title"
    render :action => "no_such_message", :status => :not_found
  end

  # Allow the user to reply to another message.
  def reply
    message = Message.find(params[:message_id])

    if message.recipient == current_user
      message.update(:message_read => true)

      @message = Message.new(
        :recipient => message.sender,
        :title => "Re: #{message.title.sub(/^Re:\s*/, '')}",
        :body => "On #{message.sent_on} #{message.sender.display_name} wrote:\n\n#{message.body.gsub(/^/, '> ')}"
      )

      @title = @message.title

      render :action => "new"
    else
      flash[:notice] = t ".wrong_user", :user => current_user.display_name
      redirect_to login_path(:referer => request.fullpath)
    end
  rescue ActiveRecord::RecordNotFound
    @title = t "messages.no_such_message.title"
    render :action => "no_such_message", :status => :not_found
  end

  # Display the list of messages that have been sent to the user.
  def inbox
    @title = t ".title"
  end

  # Display the list of messages that the user has sent to other users.
  def outbox
    @title = t ".title"
  end

  # Set the message as being read or unread.
  def mark
    @message = Message.where("to_user_id = ? OR from_user_id = ?", current_user.id, current_user.id).find(params[:message_id])
    if params[:mark] == "unread"
      message_read = false
      notice = t ".as_unread"
    else
      message_read = true
      notice = t ".as_read"
    end
    @message.message_read = message_read
    if @message.save && !request.xhr?
      flash[:notice] = notice
      redirect_to :action => :inbox
    end
  rescue ActiveRecord::RecordNotFound
    @title = t "messages.no_such_message.title"
    render :action => "no_such_message", :status => :not_found
  end

  private

  ##
  # return permitted message parameters
  def message_params
    params.require(:message).permit(:title, :body)
  rescue ActionController::ParameterMissing
    ActionController::Parameters.new.permit(:title, :body)
  end
end

openstreetmap-website/app/views/messages/_message_count.html.erb
<p id="inbox-count">
<%= t "messages.inbox.messages",
      :new_messages => t("messages.inbox.new_messages",
                         :count => current_user.new_messages.size),
      :old_messages => t("messages.inbox.old_messages",
                         :count => current_user.messages.size - current_user.new_messages.size) %>
</p>

openstreetmap-website/app/views/messages/_message_summary.html.erb
<tr id="inbox-<%= message_summary.id %>" class="inbox-row<%= "-unread" unless message_summary.message_read? %>">
  <td class="inbox-sender"><%= link_to message_summary.sender.display_name, user_path(message_summary.sender) %></td>
  <td class="inbox-subject"><%= link_to message_summary.title, message_path(message_summary) %></td>
  <td class="inbox-sent"><%= l message_summary.sent_on, :format => :friendly %></td>
  <td class="inbox-mark-unread"><%= button_to t(".unread_button"), message_mark_path(message_summary, :mark => "unread"), :remote => true, :class => "btn btn-sm btn-primary" %></td>
  <td class="inbox-mark-read"><%= button_to t(".read_button"), message_mark_path(message_summary, :mark => "read"), :remote => true, :class => "btn btn-sm btn-primary" %></td>
  <td class="inbox-destroy"><%= button_to t(".destroy_button"), message_path(message_summary, :referer => request.fullpath), :method => :delete, :remote => true, :class => "btn btn-sm btn-danger" %></td>
</tr>

openstreetmap-website/app/views/messages/_sent_message_summary.html.erb
<tr class="inbox-row">
  <td class="inbox-sender"><%= link_to sent_message_summary.recipient.display_name, user_path(sent_message_summary.recipient) %></td>
  <td class="inbox-subject"><%= link_to sent_message_summary.title, message_path(sent_message_summary) %></td>
  <td class="inbox-sent"><%= l sent_message_summary.sent_on, :format => :friendly %></td>
  <td class="inbox-destroy"><%= button_to t(".destroy_button"), message_path(sent_message_summary, :referer => request.fullpath), :method => :delete, :remote => true, :class => "btn btn-sm btn-danger" %></td>
</tr>

openstreetmap-website/app/views/messages/inbox.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "messages" %>
<% end %>

<% content_for :heading_class, "pb-0" %>

<% content_for :heading do %>
  <h1><%= t("users.show.my messages") %></h1>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active"><%= t ".my_inbox" %></a>
    </li>
    <li class="nav-item">
      <%= link_to t(".my_outbox"), outbox_messages_path, :class => "nav-link" %>
    </li>
  </ul>
<% end %>

  <h4><%= render :partial => "message_count" %></h4>

<% if current_user.messages.size > 0 %>
  <table class="table table-sm">
    <thead>
      <tr>
        <th><%= t ".from" %></th>
        <th><%= t ".subject" %></th>
        <th><%= t ".date" %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <%= render :partial => "message_summary", :collection => current_user.messages %>
    </tbody>
  </table>
<% else %>
  <div><%= t(".no_messages_yet_html", :people_mapping_nearby_link => link_to(t(".people_mapping_nearby"), user_path(current_user))) %></div>
<% end %>

openstreetmap-website/app/views/messages/new.html.erb
<% content_for :heading do %>
  <h1><%= t(".send_message_to_html", :name => link_to(@message.recipient.display_name, user_path(@message.recipient))) %></h1>
<% end %>

<%= bootstrap_form_for @message do |f| %>
  <%= hidden_field_tag :display_name, @message.recipient.display_name, :autocomplete => "off" %>
  <%= f.text_field :title %>
  <%= f.richtext_field :body, :cols => 80, :rows => 20 %>

  <%= f.primary %>
  <%= link_to t(".back_to_inbox"), inbox_messages_path, :class => "btn btn-link" %>
<% end %>

openstreetmap-website/app/views/messages/no_such_message.html.erb
<% content_for :heading do %>
  <h1><%= t ".heading" %></h1>
<% end %>

<p><%= t ".body" %></p>

openstreetmap-website/app/views/messages/outbox.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "messages" %>
<% end %>

<% content_for :heading_class, "pb-0" %>

<% content_for :heading do %>
  <h1><%= t("users.show.my messages") %></h1>

  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to t(".my_inbox"), inbox_messages_path, :class => "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link active"><%= t ".my_outbox" %></a>
    </li>
  </ul>
<% end %>

<h4><%= t ".messages", :count => current_user.sent_messages.size %></h4>

<% if current_user.sent_messages.size > 0 %>
  <table class="table table-sm">
    <thead>
      <tr>
        <th><%= t ".to" %></th>
        <th><%= t ".subject" %></th>
        <th><%= t ".date" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "sent_message_summary", :collection => current_user.sent_messages %>
    </tbody>
  </table>
<% else %>
  <div class="messages"><%= t(".no_sent_messages_html", :people_mapping_nearby_link => link_to(t(".people_mapping_nearby"), user_path(current_user))) %></div>
<% end %>

openstreetmap-website/app/views/messages/show.html.erb
<% content_for :heading do %>
  <h1><%= @message.title %></h1>
<% end %>

<% if current_user == @message.recipient %>
  <div class='info-line clearfix'>
    <%= user_thumbnail_tiny @message.sender %>
    <%= link_to @message.sender.display_name, user_path(@message.sender) %></td>
    <div class='right'>
      <%= l @message.sent_on, :format => :friendly %>
    </div>
  </div>

  <div class="richtext text-break"><%= @message.body.to_html %></div>

  <div>
    <%= link_to t(".reply_button"), message_reply_path(@message), :class => "btn btn-primary" %>
    <%= link_to t(".unread_button"), message_mark_path(@message, :mark => "unread"), :method => "post", :class => "btn btn-primary" %>
    <%= link_to t(".destroy_button"), message_path(@message), :method => "delete", :class => "btn btn-danger" %>
    <%= link_to t(".back"), inbox_messages_path, :class => "btn btn-link" %>
  </div>
<% else %>
  <div class='info-line clearfix'>
    <%= user_thumbnail_tiny @message.recipient %>
    <%= link_to @message.recipient.display_name, user_path(@message.recipient) %></td>
    <div class='right'>
      <%= l @message.sent_on, :format => :friendly %>
    </div>
  </div>

  <div class="richtext text-break"><%= @message.body.to_html %></div>

  <div>
    <%= link_to t(".destroy_button"), message_path(@message), :method => "delete", :class => "btn btn-danger" %>
    <%= link_to t(".back"), outbox_messages_path, :class => "btn btn-link" %>
  </div>
<% end %>